extends Node


signal enemy_killed(enemy)
signal gold_amount_updated()
signal gold_spent(amount)
signal reroll_cost_updated(amount)
signal current_wave_updated(wave)
signal shop_refreshed()
signal bullet_created(bullet)
signal bullet_destroyed(bullet)
signal player_health_updated(value, source)
signal player_max_health_updated(maxHealth)
signal player_death()
signal on_enemy_hit(enemy, bullet)
signal damage_done(enemy: Enemy, amount: float, type: GlobalEnums.DAMAGE_TYPES, source: String, direct: bool)
signal heal_done(amount, source)
signal armor_updated(amount, source)
signal orb_amount_increased()
signal orb_purchased()
signal orb_total_increased(nrInner, maxInner, nrOuter, maxOuter)
signal stat_updated(stat, updated_value, difference)
signal augment_recieved(augment)
signal upgrade_recieved(upgrade: Upgrade)
signal enemy_displaced(enemy: Enemy)
signal trap_landed(trap: Trap)
signal trap_expired(trap: Trap)
signal income_recieved(amount: float)
signal before_enemy_take_hit(hit: Hit, enemy: Enemy)
signal convert_hit_type(bullet)
signal refresh_shop_upgrades(current_wave: float)
signal animate_shop_upgrade_door()
