extends Node

enum PLAYER_STATS {
	ATTACK_SPEED,
	RANGE_MULTIPLER,
	DAMAGE_MULTIPLIER,
	PROJECTILE_SPEED_MULTIPLIER,
	EXTRA_PROJECTILES,
	EXTRA_CHAINS,
	ADD_MAX_HEALTH,
	ADD_HEALTH_REGENERATION,
	ADD_BASE_INCOME,
	MULTIPLY_INCOME_TIMER,
	AREA_SIZE_MULTIPLIER
}

enum ENEMY_STATUS_EFFECTS {
	FROZEN,
	SLOWED,
	ROOTED
}
