extends Node

enum PLAYER_STATS {
	ATTACK_SPEED,
	RANGE_MULTIPLER,
	DAMAGE_MULTIPLIER,
	PROJECTILE_SPEED_MULTIPLIER,
	EXTRA_PROJECTILES,
	EXTRA_CHAINS,
	ADD_MAX_HEALTH,
	ADD_HEALTH_REGENERATION,
	ADD_BASE_INCOME,
	MULTIPLY_INCOME_TIMER,
	AREA_SIZE_MULTIPLIER,
	BONUS_LUCK,
	ADD_ARMOR,
	BONUS_PIERCE,
	BONUS_BOUNCE
}

enum DAMAGE_TYPES {
	PHYSICAL,
	MAGIC,
	ICE,
	FIRE,
	POISON,
	LIGHTNING
}

enum ENEMY_STATUS_EFFECTS {
	FROZEN,
	SLOWED,
	ROOTED,
	POISONED
}

static var CROWD_CONTROL = [
	GlobalEnums.ENEMY_STATUS_EFFECTS.FROZEN,
	GlobalEnums.ENEMY_STATUS_EFFECTS.SLOWED,
	GlobalEnums.ENEMY_STATUS_EFFECTS.ROOTED
	]
